#!/bin/bash/env bash
# Function to display subdomain information
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain_list=("www" "lb-01" "web-01" "web-02")
    else
        subdomain_list=("$subdomain")
    fi

    for sub in "${subdomain_list[@]}"; do
        result=$(dig "$sub.$domain" +short)
        if [ -n "$result" ]; then
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print $4}')
            echo "The subdomain $sub is a $record_type record and points to $result"
        fi
    done
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

display_subdomain_info "$domain" "$subdomain"
