#!/usr/bin/env bash
# Update the system
sudo apt update

# Install Nginx
sudo apt install nginx -y

# Configure Nginx to add the custom header
echo 'add_header X-Served-By $hostname;' | sudo tee -a /etc/nginx/sites-available/default

# Reload Nginx to apply the changes
sudo service nginx reload
