#!/usr/bin/env bash
# Update the system
sudo apt update

# Install HAProxy
sudo apt install haproxy -y

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend web-servers

backend web-servers
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOL

# Restart HAProxy
sudo systemctl restart haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy 
