#!/usr/bin/env bash
# This Bash script generates a MySQL dump and creates a compressed archive of the dump.

mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
