#!/usr/bin/env bash
# Start Nginx to listen on port 80
service nginx start

# Check if Nginx is running on port 80
nc -z localhost 80

# Exit with success status if Nginx is listening on port 80
if [ $? -eq 0 ]; then
    echo "Nginx is now listening on port 80"
    exit 0
else
    echo "Nginx is not listening on port 80"
    exit 1
fi
