#!/usr/bin/env bash
# Function to display "To infinity and beyond" and handle SIGTERM
handle_term() {
	echo "I am invincible!!!"
	exit 0
}

# Trap the SIGTERM signal and call the handle_term function
trap handle_term SIGTERM

# This script displays "To infinity and beyond" indefinitely
while true; do
	echo "To infinity and beyond"
	sleep 2
done
