#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

# Set the counter to 1
counter=1

# Start the while loop
while [ $counter -le 10 ]
do
  echo "Best School"
  # Increment the counter
  ((counter++))
done
